name: MeSocial
options:
  minimumXcodeGenVersion: 2.39.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.nikitaumov.mesocial
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SWIFT_VERSION: 6.0
targets:
  MeSocial:
    type: application
    platform: iOS
    sources:
      - path: MeSocial
    info:
      path: MeSocial/Resources/Info.plist
    settings:
      base:
        DEVELOPMENT_TEAM: ""
